name: Android Build apk

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 自动生成 keystore（每次构建都会新生成）
      - name: Generate keystore for CI
        run: |
          keytool -genkeypair \
            -alias ci-key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore keystore.jks \
            -storepass 123456 \
            -keypass 123456 \
            -dname "CN=CI, OU=Dev, O=Company, L=City, S=State, C=CN"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease
        env:
          KEY_ALIAS: ci-key
          KEY_PASSWORD: 123456
          STORE_FILE: keystore.jks
          STORE_PASSWORD: 123456

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: frp-Android
          path: app/build/outputs/apk/release/*.apk
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: frp-Android ${{ github.ref_name }}
          files: app/build/outputs/apk/release/*.apk
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
